paths:
  # require mithril library
  'mithril': 'mithril/mithril'
  # require jquery library
  'jquery': 'jquery/dist/jquery'
  # require lodash
  'lodash': 'lodash/dist/lodash'
  # bootstrap library
  'bootstrap': 'bootstrap-sprockets'
  # alertify
  'alertify': 'alertify/alertify'
  # tweenlite
  'TweenMax': 'greensock/src/uncompressed/TweenMax'
  # slide
  'sidebar': 'jQuery.mmenu/src/js/jquery.mmenu.min.all'
shim:
  'mithril':
    exports: 'm'
  'lodash':
    exports: '_'
  'bootstrap': ['jquery']
  'TweenMax':
    exports: 'TweenMax'
  'sidebar': ['jquery']
